@extends('layouts.admin')
@php($editing = $bird->exists)
@section('title',$editing ? 'تعديل طائر' : 'إضافة طائر') @section('heading',$editing ? 'تعديل الإعلان' : 'إضافة طائر') @section('eyebrow','بيانات الطائر والوسائط')
@section('content')
<form class="admin-form" method="post" action="{{ $editing ? route('admin.birds.update',$bird) : route('admin.birds.store') }}">@csrf @if($editing)@method('put')@endif
    @if($errors->any())<div class="form-errors">{{ $errors->first() }}</div>@endif
    <section class="form-section"><div class="form-section-title"><h2>المعلومات الأساسية</h2><p>البيانات التي تظهر للمشتري في بطاقة وصفحة الطائر.</p></div><div class="form-grid">
        <label class="span-2">عنوان الإعلان<input name="title" required value="{{ old('title',$bird->title) }}" placeholder="مثال: ذكر يوركشاير أصفر مغرد"></label>
        <label>السلالة<select name="breed_id" required><option value="">اختر</option>@foreach($breeds as $breed)<option value="{{ $breed->id }}" @selected(old('breed_id',$bird->breed_id)==$breed->id)>{{ $breed->name }}</option>@endforeach</select></label>
        <label>الجنس<select name="sex" required><option value="male" @selected(old('sex',$bird->sex)==='male')>ذكر</option><option value="female" @selected(old('sex',$bird->sex)==='female')>أنثى</option><option value="unknown" @selected(old('sex',$bird->sex)==='unknown')>غير محدد</option></select></label>
        <label>اللون<input name="color" required value="{{ old('color',$bird->color) }}"></label><label>سنة الفقس<input type="number" name="hatch_year" value="{{ old('hatch_year',$bird->hatch_year) }}"></label>
        <label>مرحلة الريش<select name="molt_status"><option value="ready" @selected(old('molt_status',$bird->molt_status)==='ready')>جاهز</option><option value="young" @selected(old('molt_status',$bird->molt_status)==='young')>فرخ</option><option value="molting" @selected(old('molt_status',$bird->molt_status)==='molting')>غيار ريش</option></select></label>
        <label>التغريد<select name="singing_status"><option value="singing" @selected(old('singing_status',$bird->singing_status)==='singing')>يغرد</option><option value="not_singing" @selected(old('singing_status',$bird->singing_status)==='not_singing')>لا يغرد</option><option value="young" @selected(old('singing_status',$bird->singing_status)==='young')>فرخ</option><option value="female" @selected(old('singing_status',$bird->singing_status)==='female')>أنثى</option></select></label>
        <label>جاهزية التزاوج<select name="breeding_ready"><option value="">غير معروف</option><option value="1" @selected((string)old('breeding_ready',$bird->breeding_ready)==='1')>جاهز</option><option value="0" @selected((string)old('breeding_ready',$bird->breeding_ready)==='0')>غير جاهز</option></select></label><label>رقم الحلقة<input name="ring_number" value="{{ old('ring_number',$bird->ring_number) }}"></label>
        <label class="span-2">الوصف<textarea name="description" rows="4">{{ old('description',$bird->description) }}</textarea></label>
    </div></section>
    <section class="form-section"><div class="form-section-title"><h2>السعر والتسليم</h2><p>حدّد السعر والحالة الحالية قبل النشر.</p></div><div class="form-grid"><label>السعر<input type="number" step="0.01" name="price" required value="{{ old('price',$bird->price) }}"></label><label>العملة<input name="currency" maxlength="3" required value="{{ old('currency',$bird->currency ?: 'SAR') }}"></label><label>المدينة<input name="city" required value="{{ old('city',$bird->city) }}"></label><label>التسليم<select name="delivery_type" required><option value="pickup" @selected(old('delivery_type',$bird->delivery_type)==='pickup')>استلام شخصي</option><option value="delivery" @selected(old('delivery_type',$bird->delivery_type)==='delivery')>توصيل</option><option value="agreement" @selected(old('delivery_type',$bird->delivery_type)==='agreement')>بالاتفاق</option></select></label><label>الحالة<select name="status" required><option value="available" @selected(old('status',$bird->status ?: 'available')==='available')>متاح</option><option value="reserved" @selected(old('status',$bird->status)==='reserved')>محجوز</option><option value="sold" @selected(old('status',$bird->status)==='sold')>مباع</option></select></label><label class="check-row align-end"><input type="checkbox" name="featured" value="1" @checked(old('featured',$bird->featured))><span>إظهار ضمن الاختيارات المميزة</span></label></div></section>
    <section class="form-section"><div class="form-section-title"><h2>الصور والفيديو</h2><p>ضع كل رابط في سطر مستقل. روابط الفيديو يجب أن تكون ملفات عامة من Google Drive.</p></div><div class="form-grid"><label class="span-2">روابط الصور<textarea name="image_urls" rows="5" required placeholder="/images/birds/example.jpg&#10;https://example.com/bird.jpg">{{ old('image_urls',$bird->media?->where('type','image')->pluck('url')->join("\n")) }}</textarea></label><label class="span-2">روابط فيديو Google Drive<textarea name="video_urls" rows="4" placeholder="https://drive.google.com/file/d/.../view">{{ old('video_urls',$bird->media?->where('type','video')->pluck('url')->join("\n")) }}</textarea><small>تأكد أن صلاحية الملف: أي شخص لديه الرابط يمكنه المشاهدة.</small></label></div></section>
    <div class="form-actions"><a class="btn btn-outline" href="{{ route('admin.birds.index') }}">إلغاء</a><button class="btn btn-primary btn-large" type="submit"><i data-lucide="save"></i>{{ $editing ? 'حفظ التعديلات' : 'نشر الطائر' }}</button></div>
</form>
@endsection
