<!doctype html>
<html lang="ar" dir="rtl">
<head>
    <meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1">
    <title>@yield('title','لوحة البائع') | رفقنا</title>
    <link rel="stylesheet" href="{{ asset('admin-assets/css/bootstrap-rtl.min.css') }}">
    <link rel="stylesheet" href="{{ asset('admin-assets/css/app-rtl.min.css') }}">
    <link rel="stylesheet" href="{{ asset('admin-assets/css/canary-admin.css') }}?v=5">
</head>
<body data-sidebar="dark"><div id="layout-wrapper">
<header id="page-topbar"><div class="navbar-header"><div class="d-flex align-items-center"><button type="button" class="btn btn-sm px-3 header-item" id="vertical-menu-btn" aria-label="فتح القائمة"><i data-lucide="panel-right"></i></button><div class="d-none d-md-block ms-3"><span class="text-muted small">@yield('eyebrow','لوحة البائع')</span><h5 class="mb-0 mt-1">@yield('heading')</h5></div></div><div class="d-flex align-items-center gap-2"><a href="{{ route('home') }}" target="_blank" class="btn btn-light header-item d-none d-sm-inline-flex"><i data-lucide="external-link"></i>عرض الموقع</a><div class="header-item d-flex align-items-center gap-2"><span class="admin-avatar">{{ \Illuminate\Support\Str::substr(auth()->user()->name,0,1) }}</span><span class="d-none d-md-inline">{{ auth()->user()->sellerProfile?->display_name ?: auth()->user()->name }}</span></div><form action="{{ route('seller.logout') }}" method="post" class="m-0">@csrf<button class="btn header-item" aria-label="تسجيل الخروج"><i data-lucide="log-out"></i></button></form></div></div></header>
<aside class="vertical-menu"><div class="mobile-sidebar-head"><span><span class="admin-brand-mark"><i data-lucide="bird"></i></span> رفقنا</span><button type="button" data-sidebar-close aria-label="إغلاق القائمة"><i data-lucide="x"></i></button></div><div class="h-100"><div id="sidebar-menu"><ul class="metismenu list-unstyled" id="side-menu"><li class="menu-title">حساب البائع</li><li><a class="{{ request()->routeIs('seller.dashboard') ? 'active' : '' }}" href="{{ route('seller.dashboard') }}"><i data-lucide="layout-dashboard"></i><span>نظرة عامة</span></a></li><li><a class="{{ request()->routeIs('seller.birds.*') ? 'active' : '' }}" href="{{ route('seller.birds.index') }}"><i data-lucide="bird"></i><span>طيوري</span></a></li><li><a class="{{ request()->routeIs('seller.orders.*') ? 'active' : '' }}" href="{{ route('seller.orders.index') }}"><i data-lucide="clipboard-list"></i><span>الطلبات</span></a></li><li><a class="{{ request()->routeIs('seller.profile.*') ? 'active' : '' }}" href="{{ route('seller.profile.edit') }}"><i data-lucide="user-cog"></i><span>ملف البائع</span></a></li><li class="menu-title mt-3">روابط</li><li><a href="{{ route('sellers.show',auth()->user()) }}" target="_blank"><i data-lucide="store"></i><span>صفحتي العامة</span></a></li></ul></div></div></aside><button type="button" class="sidebar-backdrop" data-sidebar-close aria-label="إغلاق القائمة"></button>
<main class="main-content"><div class="page-content"><div class="container-fluid"><div class="d-md-none mb-4"><span class="text-muted small">@yield('eyebrow','لوحة البائع')</span><h4 class="mt-1">@yield('heading')</h4></div>@if(session('success'))<div class="alert alert-success d-flex align-items-center gap-2"><i data-lucide="circle-check"></i>{{ session('success') }}</div>@endif @yield('content')</div></div><footer class="footer"><div class="container-fluid">{{ date('Y') }} © رفقنا</div></footer></main>
</div><script>document.getElementById('vertical-menu-btn')?.addEventListener('click',function(){document.body.classList.toggle('sidebar-enable')});document.querySelectorAll('[data-sidebar-close]').forEach(function(button){button.addEventListener('click',function(){document.body.classList.remove('sidebar-enable')})});</script><script src="{{ asset('assets/js/canary.js') }}?v=3" type="module"></script></body></html>
