@extends('layouts.seller')
@php($editing=$bird->exists)
@section('title',$editing?'تعديل الطائر':'إضافة طائر') @section('heading',$editing?'تعديل الإعلان':'إضافة طائر') @section('eyebrow','بيانات الطائر والوسائط')
@section('content')
<form class="admin-form" method="post" enctype="multipart/form-data" action="{{ $editing ? route('seller.birds.update',$bird) : route('seller.birds.store') }}">@csrf @if($editing)@method('put')@endif @if($errors->any())<div class="form-errors">{{ $errors->first() }}</div>@endif
<section class="form-section"><div class="form-section-title"><h2>المعلومات الأساسية</h2><p>أدخل معلومات دقيقة؛ قد يعود الإعلان للمراجعة بعد التعديل.</p></div><div class="form-grid"><label class="span-2">عنوان الإعلان<input name="title" required value="{{ old('title',$bird->title) }}"></label><label>السلالة<select name="breed_id" required><option value="">اختر</option>@foreach($breeds as $breed)<option value="{{ $breed->id }}" @selected(old('breed_id',$bird->breed_id)==$breed->id)>{{ $breed->name }}</option>@endforeach</select></label><label>الجنس<select name="sex" required><option value="male" @selected(old('sex',$bird->sex)==='male')>ذكر</option><option value="female" @selected(old('sex',$bird->sex)==='female')>أنثى</option><option value="unknown" @selected(old('sex',$bird->sex)==='unknown')>غير محدد</option></select></label><label>اللون<input name="color" required value="{{ old('color',$bird->color) }}"></label><label>سنة الفقس<input type="number" name="hatch_year" value="{{ old('hatch_year',$bird->hatch_year) }}"></label><label>مرحلة الريش<select name="molt_status"><option value="ready" @selected(old('molt_status',$bird->molt_status)==='ready')>جاهز</option><option value="young" @selected(old('molt_status',$bird->molt_status)==='young')>فرخ</option><option value="molting" @selected(old('molt_status',$bird->molt_status)==='molting')>غيار ريش</option></select></label><label>التغريد<select name="singing_status"><option value="singing" @selected(old('singing_status',$bird->singing_status)==='singing')>يغرد</option><option value="not_singing" @selected(old('singing_status',$bird->singing_status)==='not_singing')>لا يغرد</option><option value="young" @selected(old('singing_status',$bird->singing_status)==='young')>فرخ</option><option value="female" @selected(old('singing_status',$bird->singing_status)==='female')>أنثى</option></select></label><label>جاهزية التزاوج<select name="breeding_ready"><option value="">غير معروف</option><option value="1" @selected((string)old('breeding_ready',$bird->breeding_ready)==='1')>جاهز</option><option value="0" @selected((string)old('breeding_ready',$bird->breeding_ready)==='0')>غير جاهز</option></select></label><label>رقم الحلقة<input name="ring_number" value="{{ old('ring_number',$bird->ring_number) }}"></label><label class="span-2">الوصف<textarea name="description" rows="4">{{ old('description',$bird->description) }}</textarea></label></div></section>
<section class="form-section"><div class="form-section-title"><h2>الموقع والسعر والتسليم</h2><p>المحافظة مأخوذة من ملف البائع: {{ $region->name }}</p></div><div class="form-grid"><label>اسم المدينة<input name="city" required maxlength="120" value="{{ old('city',$bird->city) }}" placeholder="مثال: جرمانا"></label><label>السعر<input type="number" step="0.01" name="price" required value="{{ old('price',$bird->price) }}"></label><label>طريقة التسليم<select name="delivery_type" required><option value="pickup" @selected(old('delivery_type',$bird->delivery_type)==='pickup')>استلام شخصي</option><option value="delivery" @selected(old('delivery_type',$bird->delivery_type)==='delivery')>توصيل</option><option value="agreement" @selected(old('delivery_type',$bird->delivery_type)==='agreement')>بالاتفاق</option></select></label></div></section>
<section class="form-section"><div class="form-section-title"><h2>الصور والفيديو</h2><p>ستُرفع الملفات مباشرة إلى Cloudinary. يمكنك رفع حتى 8 صور و3 فيديوهات.</p></div><div class="form-grid">
@if($editing && $bird->media->isNotEmpty())<div class="span-2 existing-media-grid">@foreach($bird->media as $media)<label class="existing-media-item">@if($media->type === 'image')<img src="{{ $media->url }}" alt="صورة حالية">@else<video src="{{ $media->url }}" controls preload="metadata"></video>@endif<span><input type="checkbox" name="remove_media[]" value="{{ $media->id }}"> حذف هذا الملف</span></label>@endforeach</div>@endif
<label class="span-2">صور الطائر<input type="file" name="images[]" accept=".jpg,.jpeg,.jfif,.png,.webp,.gif,.bmp,.avif,.heic,.heif" multiple @required(! $editing)><small>JPG أو PNG أو WebP أو صور الهاتف HEIC، بحد أقصى 10MB للصورة.</small></label>
<label class="span-2">فيديوهات الطائر<input type="file" name="videos[]" accept="video/mp4,video/quicktime,video/webm" multiple><small>MP4 أو MOV أو WebM، بحد أقصى 50MB للفيديو.</small></label>
</div></section>
<div class="form-actions"><a class="btn btn-outline" href="{{ route('seller.birds.index') }}">إلغاء</a><button class="btn btn-primary btn-large" type="submit"><i data-lucide="save"></i>{{ $editing?'حفظ التعديلات':'إرسال الإعلان' }}</button></div></form>
@endsection
